<?xml version="1.0" encoding="utf-8"?><Database Name="Titanic_Database" Class="LinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-MEHCO1LN\SQLEXPRESS01;Initial Catalog=Titanic_Database;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Titanic_DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Speed" Member="Speeds">
    <Type Name="Speed">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Speed" Member="Speed1" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>